<?php
// auto-generated by sfPropelAdmin
// date: 2015/06/11 17:19:41
?>
<?php echo form_tag('jurusan/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($jurusan, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('jurusan[nama]', __($labels['jurusan{nama}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('jurusan{nama}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('jurusan{nama}')): ?>
    <?php echo form_error('jurusan{nama}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($jurusan, 'getNama', array (
  'size' => 45,
  'control_name' => 'jurusan[nama]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('jurusan[created_at]', __($labels['jurusan{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('jurusan{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('jurusan{created_at}')): ?>
    <?php echo form_error('jurusan{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($jurusan, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'jurusan[created_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('jurusan[updated_at]', __($labels['jurusan{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('jurusan{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('jurusan{updated_at}')): ?>
    <?php echo form_error('jurusan{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($jurusan, 'getUpdatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'jurusan[updated_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('jurusan[fakultas_id]', __($labels['jurusan{fakultas_id}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('jurusan{fakultas_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('jurusan{fakultas_id}')): ?>
    <?php echo form_error('jurusan{fakultas_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($jurusan, 'getFakultasId', array (
  'related_class' => 'Fakultas',
  'control_name' => 'jurusan[fakultas_id]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('jurusan' => $jurusan)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($jurusan->getId()): ?>
<?php echo button_to(__('delete'), 'jurusan/delete?id='.$jurusan->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
