<?php
// auto-generated by sfPropelAdmin
// date: 2015/06/11 17:19:41
?>
<td colspan="5">
    <?php echo link_to($jurusan->getId() ? $jurusan->getId() : __('-'), 'jurusan/edit?id='.$jurusan->getId()) ?>
     - 
    <?php echo $jurusan->getNama() ?>
     - 
    <?php echo ($jurusan->getCreatedAt() !== null && $jurusan->getCreatedAt() !== '') ? format_date($jurusan->getCreatedAt(), "f") : '' ?>
     - 
    <?php echo ($jurusan->getUpdatedAt() !== null && $jurusan->getUpdatedAt() !== '') ? format_date($jurusan->getUpdatedAt(), "f") : '' ?>
     - 
    <?php echo $jurusan->getFakultasId() ?>
     - 
</td>