<?php
// auto-generated by sfPropelAdmin
// date: 2015/06/11 17:19:42
?>
    <td><?php echo link_to($jurusan->getId() ? $jurusan->getId() : __('-'), 'jurusan/edit?id='.$jurusan->getId()) ?></td>
    <td><?php echo $jurusan->getNama() ?></td>
      <td><?php echo ($jurusan->getCreatedAt() !== null && $jurusan->getCreatedAt() !== '') ? format_date($jurusan->getCreatedAt(), "f") : '' ?></td>
      <td><?php echo ($jurusan->getUpdatedAt() !== null && $jurusan->getUpdatedAt() !== '') ? format_date($jurusan->getUpdatedAt(), "f") : '' ?></td>
      <td><?php echo $jurusan->getFakultasId() ?></td>
  