<?php
// auto-generated by sfPropelAdmin
// date: 2015/06/11 17:19:41
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit jurusan', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('jurusan/edit_header', array('jurusan' => $jurusan)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('jurusan/edit_messages', array('jurusan' => $jurusan, 'labels' => $labels)) ?>
<?php include_partial('jurusan/edit_form', array('jurusan' => $jurusan, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('jurusan/edit_footer', array('jurusan' => $jurusan)) ?>
</div>

</div>
