<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/11 16:27:51

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'pgsql://postgres:admin@localhost/projek_tkbd',
), 'propel');
$this->databases['propel'] = $database;
