<?php
// auto-generated by sfPropelAdmin
// date: 2015/06/11 16:41:55
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'fakultas/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
