<?php
// auto-generated by sfPropelAdmin
// date: 2015/06/11 16:28:29
?>
    <td><?php echo link_to($fakultas->getId() ? $fakultas->getId() : __('-'), 'fakultas/edit?id='.$fakultas->getId()) ?></td>
    <td><?php echo $fakultas->getNama() ?></td>
      <td><?php echo ($fakultas->getCreatedAt() !== null && $fakultas->getCreatedAt() !== '') ? format_date($fakultas->getCreatedAt(), "f") : '' ?></td>
      <td><?php echo ($fakultas->getUpdatedAt() !== null && $fakultas->getUpdatedAt() !== '') ? format_date($fakultas->getUpdatedAt(), "f") : '' ?></td>
  