<?php
// auto-generated by sfPropelAdmin
// date: 2015/06/11 16:28:29
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/fakultas/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'fakultas/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'fakultas/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nama">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/fakultas/sort') == 'nama'): ?>
      <?php echo link_to(__('Nama'), 'fakultas/list?sort=nama&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nama'), 'fakultas/list?sort=nama&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_created_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/fakultas/sort') == 'created_at'): ?>
      <?php echo link_to(__('Created at'), 'fakultas/list?sort=created_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Created at'), 'fakultas/list?sort=created_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_updated_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/fakultas/sort') == 'updated_at'): ?>
      <?php echo link_to(__('Updated at'), 'fakultas/list?sort=updated_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/fakultas/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Updated at'), 'fakultas/list?sort=updated_at&type=asc') ?>
      <?php endif; ?>
          </th>
