propel: 
  fakultas: 
    id: ~
    nama: 
      type: VARCHAR
      size: 45
    created_at: ~
    updated_at: ~
  golongan: 
    id: ~
    kode: 
      type: VARCHAR
      size: 45
      required: true
    gaji_pokok: 
      type: DOUBLE
    gaji_sks: 
      type: DOUBLE
    gaji_sks_inggris: 
      type: DOUBLE
    created_at: ~
    updated_at: ~
  hari: 
    id: ~
    nama: 
      type: VARCHAR
      size: 45
  jam: 
    id: ~
    jam: 
      type: VARCHAR
      size: 45
  jadwal: 
    id: ~
    Jam_id: { type: integer, foreignTable: jam, foreignReference: id, required: true, onDelete: cascade }
    Hari_id: { type: integer, foreignTable: hari, foreignReference: id, required: true, onDelete: cascade }
  jurusan: 
    id: ~
    nama: 
      type: VARCHAR
      size: 45
    created_at: ~
    updated_at: ~
    Fakultas_id: { type: integer, foreignTable: fakultas, foreignReference: id, required: true, onDelete: cascade }
  matakuliah: 
    id: ~
    kodeMk: 
      type: VARCHAR
      size: 45
    nama: 
      type: VARCHAR
      size: 45
    sks: 
      type: INTEGER
    created_at: ~
    updated_at: ~
    Jurusan_id: { type: integer, foreignTable: jurusan, foreignReference: id, required: true, onDelete: cascade }
  dosen: 
    id: ~
    npk: 
      type: VARCHAR
      size: 20
      required: true
      index: unique
    nama: 
      type: VARCHAR
      size: 45
      required: true
    alamat: 
      type: LONGVARCHAR
    tgl_lahir: 
      type: DATE
    created_at: ~
    updated_at: ~
    Golongan_id: { type: integer, foreignTable: golongan, foreignReference: id, required: true, onDelete: cascade }
  slipgaji: 
    id: ~
    grand_total: 
      type: DOUBLE
    pajak: 
      type: DOUBLE
    created_at: ~
    Dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
  mahasiswa: 
    id: ~
    nrp: 
      type: VARCHAR
      size: 10
      required: true
      index: unique
    nama: 
      type: VARCHAR
      size: 45
      required: true
    alamat: 
      type: LONGVARCHAR
    tgl_lahir: 
      type: DATE
    created_at: ~
    updated_at: ~
  kelasparalel: 
    id: ~
    nama: 
      type: VARCHAR
      size: 45
    status: 
      type: 
    created_at: ~
    updated_at: ~
    MataKuliah_id: { type: integer, foreignTable: matakuliah, foreignReference: id, required: true, onDelete: cascade }
  absensi: 
    id: ~
    dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
    materi: 
      type: LONGVARCHAR
    minggu_ke: 
      type: INTEGER
    tanggal: 
      type: DATE
    sks_nyata: 
      type: INTEGER
      required: true
    jam_hadir_dosen: 
      type: TIME
    jam_keluar_dosen: 
      type: TIME
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
  kelasparalel_has_dosen: 
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
    Dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
  kelasparalel_has_jadwal: 
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
    Jadwal_id: { type: integer, foreignTable: jadwal, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    updated_at: ~
  mahasiswa_has_absensi: 
    Mahasiswa_id: { type: integer, foreignTable: mahasiswa, foreignReference: id, required: true, onDelete: cascade }
    Absensi_id: { type: integer, foreignTable: absensi, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
  mahasiswa_has_kelasparalel: 
    Mahasiswa_id: { type: integer, foreignTable: mahasiswa, foreignReference: id, required: true, onDelete: cascade }
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    updated_at: ~
  