propel: 
  fakultas: 
    id: ~
    nama: varchar(45)
    created_at: ~
    updated_at: ~
  golongan: 
    id: ~
    kode: { type: varchar(45), required: true }
    gaji_pokok: { type: numeric, size: 20, scale: 2 }
    gaji_sks: { type: numeric, size: 20, scale: 2 }
    gaji_sks_inggris: { type: numeric, size: 20, scale: 2 }
    created_at: ~
    updated_at: ~
  hari: 
    id: ~
    nama: varchar(45)
  jam: 
    id: ~
    jam: varchar(45)
  jadwal: 
    id: ~
    Jam_id: { type: integer, foreignTable: jam, foreignReference: id, required: true, onDelete: cascade }
    Hari_id: { type: integer, foreignTable: hari, foreignReference: id, required: true, onDelete: cascade }
  jurusan: 
    id: ~
    nama: varchar(45)
    created_at: ~
    updated_at: ~
    Fakultas_id: { type: integer, foreignTable: fakultas, foreignReference: id, required: true, onDelete: cascade }
  matakuliah: 
    id: ~
    kodeMk: varchar(45)
    nama: varchar(45)
    sks: integer
    created_at: ~
    updated_at: ~
    Jurusan_id: { type: integer, foreignTable: jurusan, foreignReference: id, required: true, onDelete: cascade }
  dosen: 
    id: ~
    npk: { type: varchar(20), required: true, index: unique}
    nama: { type: varchar(45), required: true}
    alamat: LONGvarchar
    tgl_lahir: DATE
    created_at: ~
    updated_at: ~
    Golongan_id: { type: integer, foreignTable: golongan, foreignReference: id, required: true, onDelete: cascade }
  slipgaji: 
    id: ~
    grand_total: { type: numeric, size: 20, scale: 2 }
    pajak:  { type: numeric, size: 20, scale: 2 }
    created_at: ~
    Dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
  mahasiswa: 
    id: ~
    nrp: { type: varchar(10), required: true, index: unique }
    nama: { type: varchar(45), required: true }
    alamat: LONGvarchar
    tgl_lahir: DATE
    created_at: ~
    updated_at: ~
  kelasparalel: 
    id: ~
    nama: varchar(45)
    status: integer
    created_at: ~
    updated_at: ~
    MataKuliah_id: { type: integer, foreignTable: matakuliah, foreignReference: id, required: true, onDelete: cascade }
  absensi: 
    id: ~
    dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
    materi: LONGvarchar
    minggu_ke: integer
    tanggal: DATE
    sks_nyata: {type: integer, required: true }
    jam_hadir_dosen: TIME
    jam_keluar_dosen: TIME
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
  kelasparalel_has_dosen: 
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
    Dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
  kelasparalel_has_jadwal: 
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
    Jadwal_id: { type: integer, foreignTable: jadwal, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    updated_at: ~
  mahasiswa_has_absensi: 
    Mahasiswa_id: { type: integer, foreignTable: mahasiswa, foreignReference: id, required: true, onDelete: cascade }
    Absensi_id: { type: integer, foreignTable: absensi, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
  mahasiswa_has_kelasparalel: 
    Mahasiswa_id: { type: integer, foreignTable: mahasiswa, foreignReference: id, required: true, onDelete: cascade }
    KelasParalel_id: { type: integer, foreignTable: kelasparalel, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    updated_at: ~
  