propel: 
  fakultas: 
    id: ~
    nama: varchar(45)
    created_at: ~
    updated_at: ~
  golongan: 
    id: ~
    kode: { type: varchar(45), required: true }
    gaji_pokok: { type: numeric, size: 20, scale: 2 }
    gaji_sks: { type: numeric, size: 20, scale: 2 }
    gaji_sks_inggris: { type: numeric, size: 20, scale: 2 }
    created_at: ~
    updated_at: ~
  hari: 
    id: ~
    nama: varchar(45)
  jam: 
    id: ~
    jam: varchar(45)
  jadwal: 
    id: ~
    jam_id: { type: integer, foreignTable: jam, foreignReference: id, required: true, onDelete: cascade }
    hari_id: { type: integer, foreignTable: hari, foreignReference: id, required: true, onDelete: cascade }
  jurusan: 
    id: ~
    nama: varchar(45)
    created_at: ~
    updated_at: ~
    fakultas_id: { type: integer, foreignTable: fakultas, foreignReference: id, required: true, onDelete: cascade }
  mata_kuliah: 
    id: ~
    kodeMk: varchar(45)
    nama: varchar(45)
    sks: integer
    created_at: ~
    updated_at: ~
    jurusan_id: { type: integer, foreignTable: jurusan, foreignReference: id, required: true, onDelete: cascade }
  dosen: 
    id: ~
    npk: { type: varchar(20), required: true, index: unique}
    nama: { type: varchar(45), required: true}
    alamat: LONGvarchar
    tgl_lahir: DATE
    created_at: ~
    updated_at: ~
    golongan_id: { type: integer, foreignTable: golongan, foreignReference: id, required: true, onDelete: cascade }
  slipgaji: 
    id: ~
    grand_total: { type: numeric, size: 20, scale: 2 }
    pajak:  { type: numeric, size: 20, scale: 2 }
    created_at: ~
    dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
  mahasiswa: 
    id: ~
    nrp: { type: varchar(10), required: true, index: unique }
    nama: { type: varchar(45), required: true }
    alamat: LONGvarchar
    tgl_lahir: DATE
    jurusan_id: { type: integer, foreignTable: jurusan, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    updated_at: ~
  kelas_palalel: 
    id: ~
    nama: varchar(45)
    status: integer
    created_at: ~
    updated_at: ~
    mata_kuliah_id: { type: integer, foreignTable: mata_kuliah, foreignReference: id, required: true, onDelete: cascade }
  absensi: 
    id: ~
    dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
    materi: LONGvarchar
    minggu_ke: integer
    tanggal: DATE
    sks_nyata: {type: integer, required: true }
    #0 = biasa , 1 = pengganti
    status: { type: integer, required: true }
    jam_hadir_dosen: TIME
    jam_keluar_dosen: TIME
    kelas_paralel_id: { type: integer, foreignTable: kelas_palalel, foreignReference: id, required: true, onDelete: cascade }
  kelas_paralel_has_dosen: 
    kelas_paralel_id: { type: integer, foreignTable: kelas_palalel, foreignReference: id, required: true, onDelete: cascade }
    dosen_id: { type: integer, foreignTable: dosen, foreignReference: id, required: true, onDelete: cascade }
  kelas_palalel_has_jadwal: 
    kelas_paralel_id: { type: integer, foreignTable: kelas_palalel, foreignReference: id, required: true, onDelete: cascade }
    jadwal_id: { type: integer, foreignTable: jadwal, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    updated_at: ~
  mahasiswa_has_absensi: 
    mahasiswa_id: { type: integer, foreignTable: mahasiswa, foreignReference: id, required: true, onDelete: cascade }
    absensi_id: { type: integer, foreignTable: absensi, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
  mahasiswa_has_kelas_palalel: 
    mahasiswa_id: { type: integer, foreignTable: mahasiswa, foreignReference: id, required: true, onDelete: cascade }
    kelas_paralel_id: { type: integer, foreignTable: kelas_palalel, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    updated_at: ~
  